"""add applications, application_events, communications

Revision ID: 78d424116366
Revises: 524a1fa660af
Create Date: 2026-09-12 14:06:10.651079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = '78d424116366'
down_revision: Union[str, None] = '524a1fa660af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# application_status is shared by three columns across two tables. Left as
# sa.Enum inside create_table, each table emits its own CREATE TYPE and the
# second fails with DuplicateObject. So every type is created exactly once up
# front, and the columns reference it with create_type=False.
application_status = postgresql.ENUM(
    'applied', 'online_assessment', 'interview', 'offer', 'rejected', 'withdrawn',
    name='application_status', create_type=False,
)
communication_kind = postgresql.ENUM(
    'email', 'call', 'meeting', 'message', 'other',
    name='communication_kind', create_type=False,
)
communication_direction = postgresql.ENUM(
    'received', 'sent', name='communication_direction', create_type=False,
)


def upgrade() -> None:
    bind = op.get_bind()
    for enum_type in (application_status, communication_kind, communication_direction):
        enum_type.create(bind, checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('resume_id', sa.Integer(), nullable=True),
    sa.Column('status', application_status, nullable=False),
    sa.Column('applied_date', sa.Date(), nullable=False),
    sa.Column('status_updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('next_action', sa.String(length=255), nullable=True),
    sa.Column('next_action_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'job_id', name='uq_application_user_job')
    )
    op.create_index(op.f('ix_applications_job_id'), 'applications', ['job_id'], unique=False)
    op.create_index(op.f('ix_applications_next_action_date'), 'applications', ['next_action_date'], unique=False)
    op.create_index(op.f('ix_applications_resume_id'), 'applications', ['resume_id'], unique=False)
    op.create_index(op.f('ix_applications_status'), 'applications', ['status'], unique=False)
    op.create_index(op.f('ix_applications_user_id'), 'applications', ['user_id'], unique=False)
    op.create_table('application_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('from_status', application_status, nullable=True),
    sa.Column('to_status', application_status, nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_events_application_id'), 'application_events', ['application_id'], unique=False)
    op.create_index(op.f('ix_application_events_changed_at'), 'application_events', ['changed_at'], unique=False)
    op.create_table('communications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('kind', communication_kind, nullable=False),
    sa.Column('direction', communication_direction, nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('contact_name', sa.String(length=200), nullable=True),
    sa.Column('subject', sa.String(length=300), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_communications_application_id'), 'communications', ['application_id'], unique=False)
    op.create_index(op.f('ix_communications_occurred_at'), 'communications', ['occurred_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_communications_occurred_at'), table_name='communications')
    op.drop_index(op.f('ix_communications_application_id'), table_name='communications')
    op.drop_table('communications')
    op.drop_index(op.f('ix_application_events_changed_at'), table_name='application_events')
    op.drop_index(op.f('ix_application_events_application_id'), table_name='application_events')
    op.drop_table('application_events')
    op.drop_index(op.f('ix_applications_user_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_status'), table_name='applications')
    op.drop_index(op.f('ix_applications_resume_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_next_action_date'), table_name='applications')
    op.drop_index(op.f('ix_applications_job_id'), table_name='applications')
    op.drop_table('applications')
    # ### end Alembic commands ###

    bind = op.get_bind()
    for enum_type in (communication_direction, communication_kind, application_status):
        enum_type.drop(bind, checkfirst=True)
