"""add job recommendation preferences to users

Revision ID: 8eba1b630d8b
Revises: 6748afe89a48
Create Date: 2026-09-12 20:17:27.478597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8eba1b630d8b'
down_revision: Union[str, None] = '6748afe89a48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('preferred_location', sa.String(length=120), nullable=True))
    op.add_column('users', sa.Column('include_remote', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'include_remote')
    op.drop_column('users', 'preferred_location')
    # ### end Alembic commands ###
