// AI-generated by Claude Sonnet 5 (Anthropic), 2026-09-12.
// Purpose: hand-drawn-style curved arrow overlay pointing from the tour
// tooltip to the highlighted element (Section 5 of the PROJECT BOOTSTRAP
// brief: "a custom SVG overlay ... quadratic/cubic bezier ... rotated
// polygon arrowhead ... pathLength stroke reveal ... seeded wobble").
// react-tourlight (see Tour.jsx) only supplies the spotlight and tooltip;
// it does not draw this connector, by design (see docs/loop/decisions.md
// D003) - this component is bespoke, not adapted from any external source.
//
// Positioned as a plain fixed-position sibling in the component tree
// (not inside the tooltip's own render-prop output) because react-tourlight
// positions its tooltip with a `transform` via Floating UI, and a CSS
// `transform` on an ancestor creates a new containing block for any
// `position: fixed` descendant - nesting the arrow inside the tooltip would
// anchor it to that transformed box instead of the viewport. Reading both
// endpoints via getBoundingClientRect() by id/selector sidesteps that.
import { useEffect, useRef, useState } from 'react'
import { TOUR_TOOLTIP_ID } from './TourTooltip.jsx'

// Matches the existing mobile breakpoint convention in styles.css
// (@media max-width: 640px). Below it, a curved line spanning the whole
// viewport reads as noise rather than a pointer, so the tour degrades to
// tooltip-only per the brief's non-negotiables.
const MOBILE_BREAKPOINT = 640

function usePrefersReducedMotion() {
  const [reduced, setReduced] = useState(
    () => typeof window !== 'undefined' && window.matchMedia('(prefers-reduced-motion: reduce)').matches
  )
  useEffect(() => {
    const mq = window.matchMedia('(prefers-reduced-motion: reduce)')
    const onChange = () => setReduced(mq.matches)
    mq.addEventListener('change', onChange)
    return () => mq.removeEventListener('change', onChange)
  }, [])
  return reduced
}

function useIsNarrowViewport(breakpoint) {
  const [narrow, setNarrow] = useState(() => typeof window !== 'undefined' && window.innerWidth < breakpoint)
  useEffect(() => {
    const onResize = () => setNarrow(window.innerWidth < breakpoint)
    window.addEventListener('resize', onResize)
    return () => window.removeEventListener('resize', onResize)
  }, [breakpoint])
  return narrow
}

// Deterministic pseudo-random in [0, 1) from a numeric seed, so a given
// step's arrow always bows the same way instead of jittering on every
// re-measure - "reads hand-drawn," not "looks broken."
function seededUnit(seed) {
  const s = Math.sin(seed) * 10000
  return s - Math.floor(s)
}

function edgePoint(rect, side) {
  switch (side) {
    case 'top':
      return { x: rect.x + rect.width / 2, y: rect.y }
    case 'bottom':
      return { x: rect.x + rect.width / 2, y: rect.y + rect.height }
    case 'left':
      return { x: rect.x, y: rect.y + rect.height / 2 }
    case 'right':
      return { x: rect.x + rect.width, y: rect.y + rect.height / 2 }
    default:
      return { x: rect.x + rect.width / 2, y: rect.y + rect.height / 2 }
  }
}

// Picks the facing edges geometrically from actual on-screen rects (rather
// than trusting the step's requested `placement`), so it stays correct even
// when Floating UI's flip() middleware moves the tooltip to the other side.
function connectingPoints(tooltipRect, targetRect) {
  const tCenter = { x: tooltipRect.x + tooltipRect.width / 2, y: tooltipRect.y + tooltipRect.height / 2 }
  const gCenter = { x: targetRect.x + targetRect.width / 2, y: targetRect.y + targetRect.height / 2 }
  const dx = gCenter.x - tCenter.x
  const dy = gCenter.y - tCenter.y

  if (Math.abs(dy) >= Math.abs(dx)) {
    return dy > 0
      ? { start: edgePoint(tooltipRect, 'bottom'), end: edgePoint(targetRect, 'top') }
      : { start: edgePoint(tooltipRect, 'top'), end: edgePoint(targetRect, 'bottom') }
  }
  return dx > 0
    ? { start: edgePoint(tooltipRect, 'right'), end: edgePoint(targetRect, 'left') }
    : { start: edgePoint(tooltipRect, 'left'), end: edgePoint(targetRect, 'right') }
}

/**
 * @param {boolean} active - whether a tour step with a resolvable target is showing
 * @param {string|undefined} targetSelector - CSS selector for the current step's target
 * @param {number} stepKey - current step index, used to reseed the wobble and replay the reveal animation
 */
export default function TourArrow({ active, targetSelector, stepKey }) {
  const [path, setPath] = useState(null)
  const rafRef = useRef(null)
  const reducedMotion = usePrefersReducedMotion()
  const narrow = useIsNarrowViewport(MOBILE_BREAKPOINT)

  useEffect(() => {
    if (!active || narrow || !targetSelector) {
      setPath(null)
      return undefined
    }

    function measure() {
      const targetEl = document.querySelector(targetSelector)
      const tooltipEl = document.getElementById(TOUR_TOOLTIP_ID)
      if (!targetEl || !tooltipEl) {
        setPath(null)
        rafRef.current = requestAnimationFrame(measure)
        return
      }

      const targetRect = targetEl.getBoundingClientRect()
      const tooltipRect = tooltipEl.getBoundingClientRect()
      const { start, end } = connectingPoints(tooltipRect, targetRect)

      const dx = end.x - start.x
      const dy = end.y - start.y
      const dist = Math.hypot(dx, dy) || 1
      const px = -dy / dist
      const py = dx / dist

      const seed = targetRect.x * 0.013 + targetRect.y * 0.029 + stepKey * 7.13
      const bow = reducedMotion ? 0 : dist * (0.14 + seededUnit(seed) * 0.12)
      const wobble = reducedMotion ? 0 : dist * (seededUnit(seed + 1) - 0.5) * 0.08

      const c1 = { x: start.x + dx * 0.3 + px * bow, y: start.y + dy * 0.3 + py * bow }
      const c2 = {
        x: start.x + dx * 0.7 + px * (bow * 0.55 + wobble),
        y: start.y + dy * 0.7 + py * (bow * 0.55 + wobble),
      }
      const angle = Math.atan2(end.y - c2.y, end.x - c2.x)

      setPath({ start, end, c1, c2, angle })
      rafRef.current = requestAnimationFrame(measure)
    }

    rafRef.current = requestAnimationFrame(measure)
    return () => {
      if (rafRef.current) cancelAnimationFrame(rafRef.current)
    }
  }, [active, narrow, targetSelector, stepKey, reducedMotion])

  if (!path) return null

  const { start, end, c1, c2, angle } = path
  const d = `M ${start.x} ${start.y} C ${c1.x} ${c1.y}, ${c2.x} ${c2.y}, ${end.x} ${end.y}`

  const headLength = 11
  const headWidth = 8
  const back = { x: end.x - headLength * Math.cos(angle), y: end.y - headLength * Math.sin(angle) }
  const left = {
    x: back.x + headWidth * Math.cos(angle + Math.PI / 2),
    y: back.y + headWidth * Math.sin(angle + Math.PI / 2),
  }
  const right = {
    x: back.x + headWidth * Math.cos(angle - Math.PI / 2),
    y: back.y + headWidth * Math.sin(angle - Math.PI / 2),
  }

  return (
    <svg className="tour-arrow" aria-hidden="true" focusable="false">
      <path
        key={stepKey}
        className={reducedMotion ? 'tour-arrow-path tour-arrow-path--static' : 'tour-arrow-path'}
        d={d}
        pathLength="1"
      />
      <polygon
        key={`head-${stepKey}`}
        className="tour-arrow-head"
        points={`${end.x},${end.y} ${left.x},${left.y} ${right.x},${right.y}`}
      />
    </svg>
  )
}
