// AI-generated by Claude Sonnet 5 (Anthropic), 2026-09-12.
// Purpose: custom tooltip card for the onboarding tour (react-tourlight's
// `renderTooltip` render prop). Styled with the app's own CSS variables
// (frontend/src/styles.css) instead of the library's default theme, so it
// matches both themes automatically. The library still owns the outer
// dialog wrapper (role="dialog", focus trap, Floating UI positioning) and
// renders this content plus its own small tooltip-arrow inside it; the
// tooltip's background/padding/shadow are zeroed via the `theme.tooltip`
// override passed into Tour.jsx so only this component's markup is visible.
//
// react-tourlight's focus trap looks for `[data-spotlight-primary]` inside
// the dialog to decide initial focus (see node_modules/react-tourlight/dist/
// use-tour-GWqnJuDb.mjs, createFocusTrap) - the Next/Done button below
// carries that attribute so keyboard users land on it immediately.
//
// `aria-labelledby`/`aria-describedby` on the library's dialog wrapper are
// only wired up automatically for its *default* tooltip content; passing a
// custom renderTooltip leaves them unset. This component sets them itself,
// imperatively, on mount - a small, self-contained fix rather than a fork.
import { useEffect, useId, useRef } from 'react'

const TOUR_TOOLTIP_ID = 'tour-tooltip-card'

export default function TourTooltip({
  step,
  next,
  previous,
  skip,
  close,
  currentIndex,
  totalSteps,
  isFirst,
  isLast,
}) {
  const titleId = useId()
  const contentId = useId()
  const rootRef = useRef(null)

  useEffect(() => {
    const dialog = rootRef.current?.closest('[role="dialog"]')
    if (!dialog) return
    dialog.setAttribute('aria-labelledby', titleId)
    dialog.setAttribute('aria-describedby', contentId)
  }, [titleId, contentId, currentIndex])

  return (
    <div id={TOUR_TOOLTIP_ID} className="tour-card" ref={rootRef}>
      <button type="button" className="tour-card-close" onClick={close} aria-label="Close tour">
        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" aria-hidden="true">
          <path d="M6 6l12 12M18 6 6 18" />
        </svg>
      </button>

      <p className="tour-card-eyebrow">
        Step {currentIndex + 1} of {totalSteps}
      </p>
      <h2 id={titleId} className="tour-card-title">
        {step.title}
      </h2>
      <p id={contentId} className="tour-card-content">
        {step.content}
      </p>

      <div className="tour-card-actions">
        <button type="button" className="btn link tour-card-skip" onClick={skip}>
          Skip tour
        </button>
        <div className="tour-card-nav">
          {!isFirst && (
            <button type="button" className="btn" onClick={previous}>
              Back
            </button>
          )}
          <button type="button" className="btn primary" onClick={next} data-spotlight-primary>
            {isLast ? 'Done' : 'Next'}
          </button>
        </div>
      </div>
    </div>
  )
}

export { TOUR_TOOLTIP_ID }
