// AI-generated by Claude Sonnet 5 (Anthropic), 2026-09-12.
// Purpose: wires react-tourlight (https://www.npmjs.com/package/react-tourlight,
// chosen over react-joyride/shepherd.js/intro.js/driver.js - see
// docs/loop/decisions.md D003 for why) into the app: the spotlight/tooltip
// engine, the custom tooltip card, the curved-arrow overlay, first-time
// auto-start, and the replayable entry point (Section 5/6 of the PROJECT
// BOOTSTRAP brief).
import { useCallback, useEffect, useRef } from 'react'
import { useNavigate } from 'react-router-dom'
import { SpotlightProvider, SpotlightTour, darkTheme, useSpotlight } from 'react-tourlight'
import 'react-tourlight/styles.css'
import { useAuth } from '../context/AuthContext.jsx'
import TourArrow from './TourArrow.jsx'
import TourTooltip, { TOUR_TOOLTIP_ID } from './TourTooltip.jsx'
import { ONBOARDING_TOUR_ID, onboardingSteps } from './tourSteps.js'

const SEEN_KEY = 'promptlyhired-onboarding-seen'

// react-tourlight always reads `theme.button.hoverBackground` etc. on the
// tooltip wrapper regardless of a custom renderTooltip (see
// node_modules/react-tourlight/dist/index.mjs, SpotlightTooltip), so a
// partial override throws. Spreading darkTheme keeps every key the library
// expects; only the visual container (which TourTooltip fully replaces) and
// the built-in pointer arrow (replaced by TourArrow) are zeroed out.
const tourTheme = {
  ...darkTheme,
  overlay: { background: 'rgba(4, 9, 20, 0.55)' },
  tooltip: {
    background: 'transparent',
    color: 'inherit',
    borderRadius: '0',
    boxShadow: 'none',
    padding: '0',
    maxWidth: 'min(360px, calc(100vw - 32px))',
  },
  arrow: { fill: 'transparent' },
}

function TourArrowBridge() {
  const { isActive, activeTourId, currentStep } = useSpotlight()
  const active = isActive && activeTourId === ONBOARDING_TOUR_ID
  const step = active ? onboardingSteps[currentStep] : undefined
  return <TourArrow active={Boolean(step)} targetSelector={step?.target} stepKey={currentStep} />
}

function TourAutoStart() {
  const { start, isActive } = useSpotlight()
  // React StrictMode double-invokes an effect with no cleanup (mount, run,
  // fake-cleanup, run again) - and calling start() twice back-to-back for
  // the same tour id makes react-tourlight stop the tour it just started
  // (start() unconditionally stops any currently-active tour before
  // creating a fresh machine; see docs/loop/decisions.md D004/D005). This
  // ref makes the second StrictMode invocation a no-op instead of a second
  // real start() call, without disabling StrictMode.
  const attemptedRef = useRef(false)

  useEffect(() => {
    if (attemptedRef.current) return
    attemptedRef.current = true
    if (isActive) return
    let seen = true
    try {
      seen = localStorage.getItem(SEEN_KEY) === 'true'
    } catch {
      // Storage can throw in private-browsing contexts; fail open (don't
      // force the tour on every load, just skip auto-start this time).
      seen = true
    }
    if (!seen) start(ONBOARDING_TOUR_ID)
    // Only ever auto-start once per mount of the authenticated app shell.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  return null
}

function markSeen() {
  try {
    localStorage.setItem(SEEN_KEY, 'true')
  } catch {
    // Hackathon-scope limitation: if storage is unavailable, the tour will
    // simply auto-start again next load. Documented in docs/loop/progress.md.
  }
}

// react-tourlight's <SpotlightTour> re-registers itself (registerTour, then
// unregisterTour on cleanup - and unregistering the *active* tour stops it,
// see node_modules/react-tourlight/dist/index.mjs) whenever any of its props
// change identity, `renderTooltip` included. An inline arrow function here
// (`renderTooltip={(props) => <TourTooltip {...props} />}`, the pattern
// shown in the library's own README) is a *new* function every render, so
// the very first re-render of TourProvider - including the one caused by
// this tour's own route-navigation steps - unregisters and stops the tour
// mid-flight. Hoisting it to a module-level constant keeps the reference
// stable across renders and was confirmed to fix the reset with a temporary
// Playwright harness during this session (see docs/loop/progress.md).
function renderTourTooltip(props) {
  return <TourTooltip {...props} />
}

export function TourProvider({ children }) {
  const navigate = useNavigate()
  // Multi-page tours (see react-tourlight's README) call this when advancing
  // to a step whose `route` doesn't match the current path - every step in
  // tourSteps.js is tagged route: '/', so replaying the tour from any page
  // sends the user to the dashboard first, then waits for the target.
  const handleNavigate = useCallback((path) => navigate(path), [navigate])

  return (
    <SpotlightProvider
      theme={tourTheme}
      navigate={handleNavigate}
      showProgress={false}
      showSkip={false}
      persist
      persistKey="promptlyhired-tour"
    >
      <SpotlightTour
        id={ONBOARDING_TOUR_ID}
        steps={onboardingSteps}
        onComplete={markSeen}
        onSkip={markSeen}
        renderTooltip={renderTourTooltip}
      />
      <TourArrowBridge />
      {children}
    </SpotlightProvider>
  )
}

export function TourAutoStartGate() {
  const { user } = useAuth()
  if (!user) return null
  return <TourAutoStart />
}

export function TourReplayButton() {
  const { user } = useAuth()
  const { start } = useSpotlight()
  if (!user) return null

  return (
    <button
      type="button"
      className="tour-replay"
      onClick={() => start(ONBOARDING_TOUR_ID, { stepIndex: 0 })}
      aria-label="Replay the onboarding tour"
      title="Replay tour"
    >
      ?
    </button>
  )
}

export { TOUR_TOOLTIP_ID }
