// AI-generated by Claude Sonnet 5 (Anthropic), 2026-09-12.
// Purpose: onboarding tour step definitions (Section 5, PROJECT BOOTSTRAP brief).
// Step targets are CSS selectors matching Dashboard.jsx / BottomNav.jsx /
// ThemeToggle.jsx on the calendar-feature lineage. All steps carry
// route: '/' so SpotlightProvider's navigate callback (wired to React
// Router in Tour.jsx) sends the user to the dashboard first, regardless of
// which page they were on when they started the tour.
export const ONBOARDING_TOUR_ID = 'onboarding'

export const onboardingSteps = [
  {
    target: '.dashboard-hero',
    route: '/',
    title: 'Welcome to PromptlyHired',
    content:
      'This is home base. Paste a job link, see how well you match it, and generate a tailored resume or cover letter in a few clicks.',
    placement: 'bottom',
  },
  {
    target: '.dashboard-primary',
    route: '/',
    title: 'Start with a job',
    content:
      'Paste a link to any posting here. PromptlyHired reads it, compares it against your resume, and shows you what matches and what is missing.',
    placement: 'bottom',
  },
  {
    target: '.dashboard-stats',
    route: '/',
    title: 'Your progress at a glance',
    content: 'Jobs added, jobs saved, and whether you have an active resume on file — all in one place.',
    placement: 'bottom',
  },
  {
    // The first card, not the whole grid: on a phone the grid is taller than the
    // screen, so a card placed beside it has nowhere to go and ends up off it.
    target: '.dashboard-grid > :first-child',
    route: '/',
    title: 'Everything else, one click away',
    content:
      'These cards jump straight to your jobs, your saved jobs, the history of documents you have generated, and your profile.',
    placement: 'top',
  },
  {
    // One nav item, not the whole nav: on desktop the nav is a full-height rail,
    // so a card placed above or below it lands off the screen, and the tour
    // could not be continued from there.
    target: '.nav a[href="/jobs"]',
    route: '/',
    title: 'Get around anytime',
    content:
      'This follows you everywhere — Jobs, Saved, History and Profile are always one tap away.',
    placement: 'top',
  },
  {
    target: '.theme-toggle',
    route: '/',
    title: 'Light or dark, your call',
    content: 'Switch themes any time. Your choice is remembered on this device.',
    // 'bottom': the toggle sits in the top corner, and on a phone there is not
    // room for the card beside it.
    placement: 'bottom',
  },
]
